far_path: all.far
example_text: |
    Arma virumque canō, Trojae quī prīmus ab ōris
    Ītaliam fātō profugus Lāvīniaque vēnit
    lītora---multum ille et terrīs jactātus et altō
    vī superum saevae memorem Jūnōnis ob īram,
    multa quoque et bellō passus, dum conderet urbem
    īnferretque deos Latio---genus unde Latīnum
    Albānīque patrēs, atque altae moenia Rōmae.
rows: 8
cols: 60
